class SessionLoadError(Exception):
    ...

class MessageSaveError(Exception):
    ...

class SessionUpdateError(Exception):
    ...

class DatabaseError(Exception):
    ...

class AgentExecutionError(Exception):
    ...